version: "3.8"
services:
  php:
    image: php:7.3-apache
    volumes:
      - ./src:/var/www/html
    ports:
      - 5050:80

  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123123
      MYSQL_ROOT_PASSWORD: 123123

  php-my-admin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
      # MYSQL_DATABASE: myDb
      MYSQL_USER: root
      MYSQL_PASSWORD: 123123
      MYSQL_ROOT_PASSWORD: 123123
      PMA_PASSWORD: 123123
    ports:
      - 8080:80
